travis:
  secure:
    BINSTAR_TOKEN: b0gE7jChyM7NdIiN+kxquGijKN7h1KD60yKOoHFWyrXoNY6h5V7yv1o+A3vftZd/Xm862NaYVgqe+/8lFtQQ+YindKnnRTUr462iUm6M6ystjfdeUewQxJvJfyjO7CXA0RfiAAGr8mato/cr/9WdGn7xHo2jDSwIU/neMMQfVUg6BI/5CmxNEfEjDMjd0lMvDwhHOTD4Xa50Lm8Sa/pfPWFQF1js6hTvd0nYEft3/8HFLbNEVKM8aDlNvR9to2Qfd4h/jBJBASG98fMCXUwpJqPwcXoZiHFcjiG2GtPl28gd4hH1sV/IbAMIFc43O/WKIV2mqwUzAqz+A9V3xbi4CQspX8PShZdwvbqww/4+Es/qjS/Hx2KoRDWQt/5obv+CPyj5aPmHcPmrBWvPVV208yTQWocd3lO7aZpTweWzNlayzzPg1EQ7X8J1/FCT3U5DlSoOQ09ZXcnRTDV4sZhlHW+bQUQKXpQ2cjbnMjlTg+aN+a4EDnDsVNSg0NIDhe2gFv1DuLZD143uvwlGVFA17PS3KE1J0ACvErIhFKrCikfBjReA7Hbc3vsq+21vfU4Fc23X/xaRTQKNz1KOEr3kR67fViTBG610znZJO5tNMcqxg7ZBb/vkIRtwGYvbn9fqIj7x97U45SHSFp6eggNQl/mVBk5EBCIb/J9+YI5MfFU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
