travis:
  secure:
    BINSTAR_TOKEN: ReR7UovmcHUeyaas1zXKo1RrIHDYH/FKBz+ANzbZ/y7cn7IBktDHuX+B5K4bivoqr66q72dMHP6eJ2djfZ5LBlpg3Ig6AIo1J9kN7ro3zTNd20onPnCx4xB+7bwtuIOdkIFlJUnIq0I6ZfuOD8SK08RVU7NKyTX6IFgb6AIf6j1KGBB5xTEwfs1KYjgCs8SkBuE1CZKSMzhi/DMVUe6Ae7H8vU+zpBGH1//3UVhwYMsNgjPf4S0vQPlkkl858JgCRb3MeVj5Z+AD3ZlLKgqxU9kT4TfhoEuKWfPEAm5QN0Rfk87ktnQpBNSxwZYyhSYxuoqJ3q/xvH3vYBS8HdYE8OHXfFjDbgY/3Tgv80UcnmQF6LCCn7HBGNV7OCX6Rz78lCxIHF50BLjeO7H5KPtd7N3RzVh+Ax+Hju1XOL+V/lJhcQ/83wr7JZXmd0YrPUE4A2cQIZDW0zcu6z4XOv7sCPQLkU0Ch+3VQoO89qHX16zcyMX7GWM4A/SaRfnZKCgoutNP/mLg8ekkOy0ELyBreV4h4P+wErGWgmFNmleXvZ14PRt5I0N5cPlTa2ZCoOnJZ2Sr70OOWqiptOLEUPDXbMyhJ+F77TnIdzouBfxrV6LCSISO+J50Ct5JXeSJRQyHf/DDVZN2pYItTuWXOnfl5ighFNTL2iGPMlEyLcKetPM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
