travis:
  secure:
    BINSTAR_TOKEN: Fma6kByWgImAYUlM6PyXPmueS0zF64AmIL9qBerspdA4GiUuCtUdEeBhJZe9j/BEnpHgkqqfyk7re9RWbjdLA7bt35Mqo1fnhTORd5MD3j2sFPzgejAwP8JBosEJjXT22EHd65TABDE3XYLcfSF0zkHdkDocJm23xaq2LWxMWMRwvKBO+slj3Qg162NGcyiqI8U6q4BAWsRcD8NjulrOiIuDGnajqPTlj/FeOZrQDqXpazkbzyhDiM7Z47ZUpH9XZwvvSrfDKyHR1PGsv8fJoefLvAjDjV9+ssX/dIygZYjbVLMzyiQXWqR0ck3zQzlgMlGVqhE4mS+ZWISWGU07uqnl10j0KXLQAJw11OLtN+g7L5dEBADnJqQ9Nwy+daJavSTkDi/9EpDw6K0IXj7/ym/IbbDvmGGV+avBvvfj84b3a4rKHNJvqDgRPUcBAlHvjl+jHe62LvzNhyJdC9PFNX3Tohdr+Mdagb8Xs66J3Cqrwq0TPtxFFEugvS5/vK/xz+2kX7PqozR6XJEzREx0A/tJ9F0Vg6C95te3RCq/UVT4GgM5NMimyinGUyIekbSX1gp1PWhRddC5/t0qf+s3uwK0/A1c2vdJfGV5nCzTzzaAZTopIbYKmmCFypu2uVVwMPoibLXgr52yV/nVt39/5LpYCg80Z4vh9uPPp8vBtcE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
